"""iniciando modelos

Revision ID: 020568ef0e13
Revises: 
Create Date: 2025-08-06 14:26:23.460193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020568ef0e13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobrenome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_endereco')
    op.drop_table('tb_aluno')
    op.drop_table('tb_pessoa')
    # ### end Alembic commands ###
