"""adicionar coluna cre aluno

Revision ID: 5ca6cc76be45
Revises: 020568ef0e13
Create Date: 2025-08-06 14:37:00.134476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca6cc76be45'
down_revision = '020568ef0e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cre', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_aluno', schema=None) as batch_op:
        batch_op.drop_column('cre')

    # ### end Alembic commands ###
